module.exports =  {
  siteName: "JPEX",
  scan: "scan",
  wait: "Coming soon",
  exchangeRate: "ExchangeRate",
  none: "",
  code: "Verification",
  send: "Verification",
  resend: "Resend in {number} second",
  welcome: "Hi,Welcome to JPEX",
  pwd: "Password",
  accounts: "Account",
  registers: "Sign up",
  regiterStep1: "Sign up now",
  regiterStep2: "Save info",
  xieyi: 'I have read and agree to the "User Agreement"',
  xieyi1: {
    first: "Nationality cannot be modified after registered",
    second: "The verification email may be judged as spam, please check",
    third: "Please keep your account information and password properly",
    fourth: "Do not use the same login password as other websites",
    fifth: "",
  }};